version: '3.6'

services:
  attack-launcher:
    build: .
    image: attack-launcher:latest
    hostname: 'attack-launcher'
    restart: always
    environment:
      - HL_USER_USERNAME=hacker
      - HL_USER_PASSWORD=compass
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.attack_router_http.rule=Host(`attack-launcher.winattacklab.local`)"
      - "traefik.http.routers.attack_router_http.entrypoints=http"       
      - "traefik.http.services.attack.loadbalancer.server.scheme=http"
