version: '3.6'

services:
  attack-launcher:
    build: .
    image: attack-launcher:latest
    hostname: 'attack-launcher'
    restart: always
    environment:
      - HL_USER_USERNAME=hacker
      - HL_USER_PASSWORD=compass
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.attack_router_http.rule=Host(`attack-launcher.winattacklab.local`)"
      - "traefik.http.routers.attack_router_http.entrypoints=http"
      - "traefik.http.routers.attack_router_http.middlewares=redirect@file"
      - "traefik.http.routers.attack_router_https.entrypoints=https"
      - "traefik.http.routers.attack_router_https.rule=Host(`attack-launcher.winattacklab.local`)"
      - "traefik.http.routers.attack_router_https.tls=true"
      - "traefik.http.services.attack-launcher.loadbalancer.server.port=80"
      - "traefik.http.services.attack-launcher.loadbalancer.server.scheme=http"
