## Setting up the middleware for redirect to https ##
http:
  middlewares:
    redirect:
      redirectScheme:
        scheme: https

## DYNAMIC CONFIG

tls:
  certificates:
    - certFile: /certs/cert.crt
      keyFile: /certs/cert.key
      stores:
       - default
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.crt
        keyFile: /certs/cert.key

# source: https://community.traefik.io/t/error-with-custom-tls-certs/2356/3
