#!/bin/bash

cd /winattacklab/

echo "=========================="
echo "SSH attack"
echo "=========================="
sleep 1

echo "launching ssh attack"
client_ip=10.0.1.15
for (( i=0; i<10; ++i)); do
    ssh -o "StrictHostKeyChecking no" john@$client_ip
done


