#!/bin/bash

# RDP Bruteforce Attack

cd /winattacklab/

echo "=========================="
echo "RDP attack"
echo "=========================="
sleep 1

echo "click on \"Run Task\" to run the RDP attack ..."
