#!/bin/bash

cd /winattacklab/

shuf -n 10 /opt/rbl/urlhaus.txt > /opt/rbl/shuf.csv_recents.txt
shuf -n 10 /opt/rbl/downloads.txt > /opt/rbl/shuf.downloads.txt

echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
echo "`date`: csv recents" >> /opt/rbl/rbl-history.txt
echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
cat /opt/rbl/shuf.csv_recents.txt >> /opt/rbl/rbl-history.txt

echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
echo "`date`: downloads" >> /opt/rbl/rbl-history.txt
echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
cat /opt/rbl/shuf.downloads.txt >> /opt/rbl/rbl-history.txt


lines=$(cat /opt/rbl/shuf.csv_recents.txt)
for line in $lines; do
        curl -s -m 5 --dns-servers 10.0.1.100 http://$line;
        curl -s -m 5 --dns-servers 10.0.1.100 https://$line -k;
        dig -x +short +time=5 +tries=1 @10.0.1.100 $line;
done

lines=$(cat /opt/rbl/shuf.downloads.txt)
for line in $lines; do
        curl -s -m 5 --dns-servers 10.0.1.100 $line -k;
done
