#!/bin/bash

# Request latest malicious ip addresses

cd /winattacklab/

echo "======================================="
echo "Latest 10 addresses from https://urlhaus.abuse.ch/downloads/csv_recent/"
cat /opt/rbl/shuf.csv_recents.txt

echo "======================================="
echo "Latest 10 addresses from https://urlhaus.abuse.ch/downloads/text/"
cat /opt/rbl/shuf.downloads.txt

echo "======================================="
echo "Click on Run Task to make web requests to the listed addresses above"
sleep 2s
echo "The history of all picked addresses from URLhaus..."
sleep 2s
cat /opt/rbl/rbl-history.txt



