#!/bin/bash

# Request latest malicious ip addresses

cd /winattacklab/

echo "Executing requests on following malicious ip addresses..."
lines=$(cat /opt/rbl/shuf.csv_recents.txt)
echo "$lines"

for line in $lines; do
    curl -s -m 5 --dns-servers 10.0.1.100 http://$line;
    curl -s -m 5 --dns-servers 10.0.1.100 https://$line -k;
    dig -x +short +time=5 +tries=1 @10.0.1.100 $line;
done

echo "Executing requests on following 10 malicious ip addresses..."
lines=$(cat /opt/rbl/shuf.downloads.txt)
echo "$lines"

for line in $lines; do
    curl -s -m 5 --dns-servers 10.0.1.100 $line -k;
done
