#!/bin/bash

# Request new malicious ip addresses

cd /winattacklab/

shuf -n 10 /opt/rbl/urlhaus.txt > /opt/rbl/shuf.csv_recents.txt
echo "Picking 10 malicious ip addresses at random from https://urlhaus.abuse.ch/downloads/csv_recent/..."
cat /opt/rbl/shuf.csv_recents.txt

shuf -n 10 /opt/rbl/downloads.txt > /opt/rbl/shuf.downloads.txt
echo "Picking 10 malicious ip addresses at random from https://urlhaus.abuse.ch/downloads/text/..."
cat /opt/rbl/shuf.downloads.txt

echo "Reload this page if you want new ip addresses"

echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
echo "`date`: csv recents" >> /opt/rbl/rbl-history.txt
echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
cat /opt/rbl/shuf.csv_recents.txt >> /opt/rbl/rbl-history.txt

echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
echo "`date`: downloads" >> /opt/rbl/rbl-history.txt
echo "`date`: ===============================" >> /opt/rbl/rbl-history.txt
cat /opt/rbl/shuf.downloads.txt >> /opt/rbl/rbl-history.txt
