#!/bin/bash

cd /winattacklab/

shuf -n 10 /opt/rbl/urlhaus.txt > /opt/rbl/rbl.txt
for line in "`cat `"; do curl -m 5 http://$line; curl -m 5 https://$line; dig -x +time=5 +tries=1 @10.1.10.100 $line; done

