#!/bin/bash

# Request new malicious ip addresses

cd /winattacklab/

echo "Executing web requests on following 10 malicious ip addresses..."

lines=$(cat /opt/rbl/shuf.csv_recents.txt)
echo "$lines"

for line in $lines; do 
    echo "Requesting http://$line"
    curl -k -m 5 http://$line
    echo "Requesting https://$line"
    curl -k -m 5 https://$line
    echo "Reverse Lookup of $line"
    dig -x +short +time=5 +tries=1 @10.0.1.100 $line; 
done


